# Generated by Django 3.1.3 on 2020-12-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country code', max_length=5)),
                ('address', models.CharField(default='Unknown', help_text='Property Location', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in doller', max_digits=10)),
                ('image', models.CharField(default='https://images.unsplash.com/photo-1579700432983-39c5fb5815e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1486&q=80', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Dummy Properties',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_no', models.IntegerField(verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('pin_code', models.IntegerField(help_text='PIN/ZIP Code')),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('is_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=120, null=True)),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True, verbose_name='Property Age')),
                ('bhk', models.IntegerField(blank=True, help_text='BHK', null=True, verbose_name='BHK')),
                ('typ', models.CharField(blank=True, help_text='Property Type', max_length=20, null=True, verbose_name='Type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('specifications', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('limitations', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Response Form',
                'verbose_name_plural': 'Response Forms',
            },
        ),
    ]
