# Generated by Django 3.1.3 on 2020-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country code', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in doller', max_digits=10)),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
    ]
