# Generated by Django 3.1.3 on 2020-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummyproperty',
            options={'verbose_name_plural': 'Dummy Properties'},
        ),
        migrations.AlterField(
            model_name='dummyproperty',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
