# Generated by Django 3.1.3 on 2020-11-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummyproperty',
            options={'verbose_name_plural': 'Dummy Properties'},
        ),
        migrations.AlterField(
            model_name='dummyproperty',
            name='image',
            field=models.CharField(default='https://images.unsplash.com/photo-1579700432983-39c5fb5815e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1486&q=80', max_length=255),
        ),
    ]
