# Generated by Django 3.1.3 on 2020-11-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201122_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Property Age'),
        ),
        migrations.AlterField(
            model_name='response',
            name='bhk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
