# Generated by Django 3.1.3 on 2020-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='query',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
