# Generated by Django 3.1.3 on 2020-11-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_response_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyproperty',
            name='address',
            field=models.CharField(default='Unknown', help_text='Property Location', max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='bhk',
            field=models.IntegerField(blank=True, help_text='BHK', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='typ',
            field=models.CharField(blank=True, help_text='Property Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(help_text='PIN/ZIP Code'),
        ),
    ]
