# Generated by Django 3.1.3 on 2020-11-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201124_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='bhk',
            field=models.IntegerField(blank=True, help_text='BHK', null=True, verbose_name='BHK'),
        ),
        migrations.AlterField(
            model_name='response',
            name='typ',
            field=models.CharField(blank=True, help_text='Property Type', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
